// Content for the three stone detail pages. Theme decides the page palette:
// "light" = ink on paper, "dark" = paper on ink, "verde" = paper on deep green.

export const stones = [
  {
    slug: 'calacatta-oro',
    name: 'Calacatta Oro',
    h1: ['calacatta', 'oro'],
    n: '01',
    theme: 'light',
    hero: 'calacatta-oro.jpg',
    heroAlt: 'A full slab of Calacatta Oro: bright white marble crossed by a broad vein of grey and gold',
    lead: ['A bright white ground, crossed by broad veins that run from soft grey', 'into gold.'],
    body: 'Calacatta Oro is quarried in the Apuan Alps above Carrara, and it is far scarcer than the Carrara marble that shares its mountains. The veins are few and bold, so each slab reads as a single drawing — which is why it is so often book-matched across a wall.',
    facts: [
      ['Origin', 'Apuan Alps, Tuscany, Italy'], ['Stone', 'Marble'], ['Ground', 'Bright white'],
      ['Veining', 'Broad and bold, grey into gold'], ['Finishes', 'Polished, honed, brushed, bush-hammered'], ['Formats', 'Slabs, tiles, cut-to-size'],
    ],
    detail: 'calacatta-detail.jpg',
    detailAlt: 'Close view of Calacatta Oro: a gold vein crossing the white ground',
    pins: [[70, 14], [30, 41], [18, 80]],
    read: [
      ['The ground', 'A bright, even white, with only a faint grey cloud.'],
      ['The vein', 'Broad and smoky, running from grey into honey and gold.'],
      ['The feathering', 'Hair-fine secondary veins that trail away from the main one.'],
    ],
    finishes: [
      ['polished', 'Polished', 'Mirror gloss. The deepest colour and the sharpest vein.'],
      ['honed', 'Honed', 'Smooth and matte. Softer light, quieter contrast.'],
      ['brushed', 'Brushed', 'A gentle, worn-in texture with a satin sheen.'],
      ['hammered', 'Bush-hammered', 'Pitted and pale. Sure grip for steps and terraces.'],
    ],
    layout: 'calacatta-layout.jpg',
    quadPos: '100% 100%',
    rooms: [
      ['Feature walls', 'Book-matched pairs turn the vein into the centrepiece.'],
      ['Worktops and islands', 'Seal it, and wipe citrus or wine promptly: marble is sensitive to acids.'],
      ['Bathrooms', 'Vanity tops, shower walls and floors.'],
      ['Floors', 'Honed, for a softer sheen and a surer step.'],
      ['Stairs and sills', 'Cut to size, with the vein carried from tread to tread.'],
      ['Fireplaces and furniture', 'Surrounds, table tops and shelves.'],
    ],
    pairs: [
      ['nero-marquina.html', 'nero-marquina.jpg', '02', 'Nero Marquina', 'The classic contrast: black against white.'],
      ['verde-alpi.html', 'verde-alpi.jpg', '03', 'Verde Alpi', 'Deep green beside the white, for borders and inlay.'],
      ['collection.html', 'emperador-dark.jpg', '07', 'Emperador Dark', 'Warm brown that picks up the gold in the vein.'],
    ],
    sphere: 'calacatta-sphere.webp',
  },
  {
    slug: 'nero-marquina',
    name: 'Nero Marquina',
    h1: ['nero', 'marquina'],
    n: '02',
    theme: 'dark',
    hero: 'nero-marquina.jpg',
    heroAlt: 'A full slab of Nero Marquina: deep black marble struck through with white veins',
    lead: ['Deep black, struck through with white calcite. Few stones draw', 'a sharper line.'],
    body: 'Nero Marquina comes from the hills around Markina, in the Basque Country of northern Spain. It is a fine-grained black stone crossed by irregular white veins. Polished, it turns almost mirror-black; honed, it softens toward charcoal.',
    facts: [
      ['Origin', 'Markina, Basque Country, Spain'], ['Stone', 'Marble'], ['Ground', 'Deep, even black'],
      ['Veining', 'Sharp white calcite, bold to hair-fine'], ['Finishes', 'Polished, honed, brushed, bush-hammered'], ['Formats', 'Slabs, tiles, cut-to-size'],
    ],
    detail: 'nero-detail.jpg',
    detailAlt: 'Close view of Nero Marquina: a broad white vein crossing the black ground',
    pins: [[22, 62], [36, 20], [78, 14]],
    read: [
      ['The ground', 'Dense, even black, with a fine grain.'],
      ['The lightning', 'White calcite veins, from finger-wide to hair-fine.'],
      ['The web', 'A faint net of fissures between the main veins.'],
    ],
    finishes: [
      ['polished', 'Polished', 'Mirror gloss. The blackest black and the brightest vein.'],
      ['honed', 'Honed', 'Smooth and matte. The black softens toward charcoal.'],
      ['brushed', 'Brushed', 'A gentle, worn-in texture with a satin sheen.'],
      ['hammered', 'Bush-hammered', 'Pitted, and pale grey rather than black. Sure grip for steps.'],
    ],
    layout: 'nero-layout.jpg',
    quadPos: '100% 46%',
    rooms: [
      ['Chequerboard floors', 'The classic partner to white marble, tile against tile.'],
      ['Bathrooms', 'Vanity tops, basin surrounds and wall cladding.'],
      ['Worktops and bars', 'Seal it: acids leave pale marks, and they show on black.'],
      ['Feature walls', 'Book-matched, the white veins join into one figure.'],
      ['Stairs and thresholds', 'Honed or brushed, for grip and a softer black.'],
      ['Tables and plinths', 'A dark base that makes whatever stands on it stand out.'],
    ],
    pairs: [
      ['calacatta-oro.html', 'calacatta-oro.jpg', '01', 'Calacatta Oro', 'White and gold against the black.'],
      ['collection.html', 'bianco-carrara.jpg', '04', 'Bianco Carrara', 'The chequerboard partner.'],
      ['collection.html', 'portoro.jpg', '05', 'Portoro', 'Black on black, with a seam of gold.'],
    ],
    sphere: 'nero-sphere.webp',
  },
  {
    slug: 'verde-alpi',
    name: 'Verde Alpi',
    h1: ['verde', 'alpi'],
    n: '03',
    theme: 'verde',
    hero: 'verde-alpi.jpg',
    heroAlt: 'A full slab of Verde Alpi: deep green marble held in a net of pale veins',
    lead: ['Alpine green: dark serpentine, held in', 'a net of pale veins.'],
    body: 'Verde Alpi is quarried in the Aosta Valley, in the Italian Alps. It is a serpentine marble: angular green fragments bound together by veins of white and pale-green calcite. Dark, dense and full of movement, it has long been used for columns, floors and inlay.',
    facts: [
      ['Origin', 'Aosta Valley, Italy'], ['Stone', 'Serpentine marble'], ['Ground', 'Deep green, mottled'],
      ['Veining', 'A net of white and pale green'], ['Finishes', 'Polished, honed, brushed, bush-hammered'], ['Formats', 'Slabs, tiles, cut-to-size'],
    ],
    detail: 'verde-detail.jpg',
    detailAlt: 'Close view of Verde Alpi: a white calcite vein crossing dark green serpentine',
    pins: [[80, 60], [50, 40], [20, 28]],
    read: [
      ['The ground', 'Dark green serpentine, mottled like moss.'],
      ['The net', 'Calcite veins, white running into pale green.'],
      ['The clasts', 'Angular fragments, each a slightly different green.'],
    ],
    finishes: [
      ['polished', 'Polished', 'Mirror gloss. The green at its deepest, almost like a gemstone.'],
      ['honed', 'Honed', 'Smooth and matte. A softer, greyer green.'],
      ['brushed', 'Brushed', 'A gentle, worn-in texture with a satin sheen.'],
      ['hammered', 'Bush-hammered', 'Pitted, and pale grey-green. Sure grip for steps.'],
    ],
    layout: 'verde-layout.jpg',
    quadPos: '100% 70%',
    rooms: [
      ['Floors and borders', 'Framing a white floor, or inlaid as a single band.'],
      ['Bathrooms', 'Wall cladding and vanity tops with real depth.'],
      ['Bar tops and tables', 'Polished, it reads almost like a gemstone.'],
      ['Feature walls', 'Book-matched, the net of veins turns symmetrical.'],
      ['Columns and plinths', 'A traditional use: dark, dense and monumental.'],
      ['Fireplaces', 'Surrounds and hearths.'],
    ],
    pairs: [
      ['calacatta-oro.html', 'calacatta-oro.jpg', '01', 'Calacatta Oro', 'White and gold against the green.'],
      ['collection.html', 'bianco-carrara.jpg', '04', 'Bianco Carrara', 'Cool grey-white: the quiet partner.'],
      ['collection.html', 'rosso-levanto.jpg', '06', 'Rosso Levanto', 'Its red sister stone, from Liguria.'],
    ],
    sphere: 'verde-sphere.webp',
  },
];
